
-- 1 --
CREATE TABLE T_USER (
	UNO				VARCHAR2(20) 	PRIMARY KEY NOT NULL,
	UPWD			VARCHAR2(128)	DEFAULT 'ssg2017' NOT NULL,
	UNAME			VARCHAR2(20)	NOT NULL,
	UEMAIL			VARCHAR2(100)	NOT NULL,
	UPHONE			NUMBER(11)		NOT NULL,
	UACCOUNT		VARCHAR2(100)	NOT NULL,
	UMONEY			NUMBER			DEFAULT 0 NOT NULL,
	REGDATE			DATE			DEFAULT SYSDATE,
	MODDATE			DATE
);

DROP TABLE T_USER CASCADE CONSTRAINT;

-- 2 --
CREATE TABLE T_EVENT_ATT (
	EANO			NUMBER			NOT	NULL,
	EACNT			NUMBER			DEFAULT 0 NOT NULL,
	EAATTCNT		NUMBER			DEFAULT 0 NOT NULL,
	EAHISTDATE		DATE			DEFAULT SYSDATE,
	REGDATE			DATE			DEFAULT SYSDATE,
	MODDATE			DATE,
	UNO				VARCHAR2(20)	REFERENCES	T_USER(UNO)	NOT NULL
);

DROP TABLE T_EVENT_ATT CASCADE CONSTRAINT;

-- 3 -- 
CREATE SEQUENCE SEQ_EVENT_ATT
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE;
	
DROP SEQUENCE SEQ_EVENT_ATT;
	
-- 4 --
CREATE TABLE T_USER_LOTTO (
	ULNO			NUMBER		  PRIMARY KEY NOT NULL,
	ULNAME			VARCHAR2(100) NOT NULL,
	ULNUM1          NUMBER		  NOT NULL,
	ULNUM2          NUMBER    	  NOT NULL,
	ULNUM3          NUMBER    	  NOT NULL,
	ULNUM4          NUMBER    	  NOT NULL,
	ULNUM5          NUMBER    	  NOT NULL,
	ULNUM6          NUMBER    	  NOT NULL,
	REGDATE			DATE		  DEFAULT SYSDATE,
	MODDATE			DATE,
	UNO				VARCHAR2(20)  REFERENCES	T_USER(UNO)	NOT NULL
);	

DROP TABLE T_USER_LOTTO CASCADE CONSTRAINT;

-- 5 --
CREATE SEQUENCE SEQ_USER_LOTTO
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE;
	
DROP SEQUENCE SEQ_USER_LOTTO;
	
-- 6 --
CREATE TABLE T_USER_COUPON (
	UCNO			NUMBER			PRIMARY KEY NOT NULL,
	UCNAME			VARCHAR2(100)	NOT NULL,
	UCBUYCATE		VARCHAR2(100)	,
	UCMARKETCATE	VARCHAR2(100)	,
	REGDATE			DATE			DEFAULT SYSDATE,
	MODDATE			DATE,
	UNO				VARCHAR2(20)	REFERENCES	T_USER(UNO)	NOT NULL
);	

DROP TABLE T_USER_COUPON CASCADE CONSTRAINT;
	
-- 7 --
CREATE SEQUENCE SEQ_USER_COUPON
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE;
	
DROP SEQUENCE SEQ_USER_COUPON;
	
-- 8 --	
CREATE TABLE T_BUYINFO (
	BNO				NUMBER			PRIMARY KEY NOT NULL,
	BBUYCATE		VARCHAR2(100)	NOT NULL,
	BMARKETCATE		VARCHAR2(100)	NOT NULL,
	REGDATE			DATE			DEFAULT SYSDATE,
	MODDATE			DATE,
	UNO				VARCHAR2(20)	REFERENCES	T_USER(UNO)	NOT NULL
);	

DROP TABLE T_BUYINFO CASCADE CONSTRAINT;

-- 9 --
CREATE SEQUENCE SEQ_BUYINFO
	START WITH 1
	INCREMENT BY 1
	NOCYCLE
	NOCACHE;
	
DROP SEQUENCE SEQ_BUYINFO;